import { defineStore } from 'pinia'
import { useItemStore as itemStore } from '@/stores/inventory'

export const useShopStore = defineStore('shopStore', {
  state: () => ({
    skills: [
      {
        id: 'combatshop',
        name: 'Combat',
        image: 'assets/12x/combat.png',
        price1: ['money', 10, 'resourceItems'],
        price2: ['meatChop', 1, 'consumableItems'],
        unlocks: [-99], //hardcoded to unlock combat
        sequence: 0,
        isInGame: true,
        requiresCombat: false,
      },
      {
        id: 'rangedshop',
        name: 'Ranged',
        image: 'assets/12x/ranged.png',
        price1: ['money', 400, 'resourceItems'],
        price2: ['copperArrow', 1, 'equipmentItems'],
        unlocks: [2, 5],
        sequence: 0,
        isInGame: true,
        requiresCombat: true,
      },
      {
        id: 'magicshop',
        name: 'Magic',
        image: 'assets/12x/spirit.png',
        price1: ['money', 800, 'resourceItems'],
        price2: ['charge1', 1, 'equipmentItems'],
        unlocks: [3, 6],
        sequence: 0,
        isInGame: true,
        requiresCombat: true,
      },
      {
        id: 'smithingshop',
        name: 'Smithing',
        image: 'assets/12x/smithing.png',
        price1: ['money', 10, 'resourceItems'],
        price2: ['ore1', 1, 'resourceItems'],
        unlocks: [16],
        sequence: 0,
        isInGame: true,
        requiresCombat: false,
      },
      {
        id: 'artificeshop',
        name: 'Artifice',
        image: 'assets/12x/artiface.png',
        price1: ['money', 1200, 'resourceItems'],
        price2: ['rune1', 1, 'resourceItems'],
        unlocks: [18],
        sequence: 0,
        isInGame: true,
        requiresCombat: false,
      },
      {
        id: 'cookingshop',
        name: 'Cooking',
        image: 'assets/12x/cooking.png',
        price1: ['money', 50, 'resourceItems'],
        price2: ['plant1', 1, 'resourceItems'],
        unlocks: [20],
        sequence: 0,
        isInGame: true,
        requiresCombat: false,
      },
      {
        id: 'tailoringshop',
        name: 'Tailoring',
        image: 'assets/12x/tailoring.png',
        price1: ['money', 1200, 'resourceItems'],
        price2: ['wool', 3, 'resourceItems'],
        unlocks: [19],
        sequence: 3,
        isInGame: false,
        requiresCombat: false,
      },
      {
        id: 'fletchingshop',
        name: 'Fletching',
        image: 'assets/12x/fletching.png',
        price1: ['money', 1200, 'resourceItems'],
        price2: ['feather', 15, 'resourceItems'],
        unlocks: [17],
        sequence: 3,
        isInGame: false,
        requiresCombat: false,
      },
      {
        id: 'alchemyshop',
        name: 'Alchemy',
        image: 'assets/12x/alchemy.png',
        price1: ['money', 2000, 'resourceItems'],
        price2: ['rune2', 1, 'resourceItems'],
        unlocks: [21],
        sequence: 3,
        isInGame: false,
        requiresCombat: false,
      },
    ],
    items0: [
      {
        id: 'stew',
        name: "Traveler's Stew",
        image: 'assets/icons/rawchop.png',
        price: '24',
      },
      {
        id: 'trinketSpice',
        name: 'Spice Pouch',
        image: 'assets/icons/rawchop.png',
        price: '480',
      },
    ],
    items1: [
      {
        id: 'oil1',
        name: 'Slip Oil',
        image: '',
        price: '7',
      },
      {
        id: 'copperArrow',
        name: 'Copper Arrows',
        image: 'assets/icons/copperarrow.png',
        price: '4',
      },
      {
        id: 'charge1',
        name: 'Strike Charge',
        image: 'assets/icons/charge1.png',
        price: '10',
      },
    ],
  }),
  getters: {
  },
  actions: {
  }
})