import { defineStore } from 'pinia'
import { useItemStore as itemStore } from '@/stores/inventory'

export const useShopStore = defineStore('shopStore', {
  state: () => ({
    skills: [
      // {
      //   id: 'combatshop',
      //   name: 'Combat',
      //   image: 'assets/12x/combat.png',
      //   price1: ['money', 10, 'resourceItems'],
      //   price2: ['meatChop', 1, 'consumableItems'],
      //   unlocks: [-99], //hardcoded to unlock combat
      //   sequence: 0,
      //   isInGame: true,
      //   requiresCombat: false,
      // },
      {
        id: 'meleeshop',
        name: 'Melee',
        image: 'assets/12x/strength.png',
        price1: ['money', 10, 'resourceItems'],
        price2: ['copperDagger', 1, 'equipmentItems'],
        unlocks: [1, 4],
        sequence: 0,
        isInGame: true,
        requiresCombat: true,
      },
      {
        id: 'rangedshop',
        name: 'Ranged',
        image: 'assets/12x/ranged.png',
        price1: ['money', 400, 'resourceItems'],
        price2: ['copperArrow', 1, 'equipmentItems'],
        unlocks: [2, 5],
        sequence: 0,
        isInGame: true,
        requiresCombat: true,
      },
      {
        id: 'magicshop',
        name: 'Magic',
        image: 'assets/12x/spirit.png',
        price1: ['money', 800, 'resourceItems'],
        price2: ['charge1', 1, 'equipmentItems'],
        unlocks: [3, 6],
        sequence: 0,
        isInGame: true,
        requiresCombat: true,
      },
      {
        id: 'smithingshop',
        name: 'Smithing',
        image: 'assets/12x/smithing.png',
        price1: ['money', 10, 'resourceItems'],
        price2: ['ore1', 1, 'resourceItems'],
        unlocks: [16],
        sequence: 0,
        isInGame: true,
        requiresCombat: false,
      },
      {
        id: 'artificeshop',
        name: 'Artifice',
        image: 'assets/12x/artiface.png',
        price1: ['money', 1200, 'resourceItems'],
        price2: ['rune1', 1, 'resourceItems'],
        unlocks: [18],
        sequence: 0,
        isInGame: true,
        requiresCombat: false,
      },
      {
        id: 'cookingshop',
        name: 'Cooking',
        image: 'assets/12x/cooking.png',
        price1: ['money', 50, 'resourceItems'],
        price2: ['plant1', 1, 'resourceItems'],
        unlocks: [20],
        sequence: 0,
        isInGame: true,
        requiresCombat: false,
      },
      {
        id: 'tailoringshop',
        name: 'Tailoring',
        image: 'assets/12x/tailoring.png',
        price1: ['money', 1200, 'resourceItems'],
        price2: ['wool', 3, 'resourceItems'],
        unlocks: [19],
        sequence: 3,
        isInGame: false,
        requiresCombat: false,
      },
      {
        id: 'fletchingshop',
        name: 'Fletching',
        image: 'assets/12x/fletching.png',
        price1: ['money', 1200, 'resourceItems'],
        price2: ['feather', 15, 'resourceItems'],
        unlocks: [17],
        sequence: 3,
        isInGame: false,
        requiresCombat: false,
      },
      {
        id: 'alchemyshop',
        name: 'Alchemy',
        image: 'assets/12x/alchemy.png',
        price1: ['money', 2000, 'resourceItems'],
        price2: ['rune2', 1, 'resourceItems'],
        unlocks: [21],
        sequence: 3,
        isInGame: false,
        requiresCombat: false,
      },
      {
        id: 'craftingshop',
        name: 'Crafting',
        image: 'assets/12x/crafting.png',
        price1: ['money', 2000, 'resourceItems'],
        price2: ['glassBar', 1, 'resourceItems'],
        unlocks: [22],
        sequence: 3,
        isInGame: false,
        requiresCombat: false,
      },
    ],
    items: [
      {
        id: 'stew',
        price: '24',
        sequence: 0,
      },
      {
        id: 'oil1',
        image: '',
        price: '7',
        sequence: 3,
      },
      {
        id: 'copperArrow',
        price: '4',
        sequence: 3,
      },
      {
        id: 'charge1',
        price: '10',
        sequence: 3,
      },
    ],
    equipment: [
      {
        id: 'trinketSpice',
        price1: ['money', 480, 'resourceItems'],
        sequence: 0,
      },
      {
        id: 'bronzeCook',
        price1: ['money', 200, 'resourceItems'],
        price2: ['bar2', 8, 'resourceItems'],
        sequence: 0,
      },
      {
        id: 'ironCook',
        price1: ['money', 320, 'resourceItems'],
        price2: ['bar3', 8, 'resourceItems'],
        sequence: 3,
      },
      {
        id: 'steelCook',
        price1: ['money', 600, 'resourceItems'],
        price2: ['bar5', 8, 'resourceItems'],
        sequence: 6,
      },
      {
        id: 'mythrilCook',
        price1: ['money', 850, 'resourceItems'],
        price2: ['bar6', 8, 'resourceItems'],
        sequence: 6,
      },
    ],
  }),
  getters: {
  },
  actions: {
  }
})